### ISSUE TITLE
[Feature] Secondary Modifier Key Carry-Over

### ISSUE THREAD

**Issue by Julian-B** [baxter-oop/AndOre#131]
Just a simple tweak, but...

Say I build a Mine/Factory with `b-3`. Then I press `m` to move, and walk to my left. My status bar now returns to`m-1`. If I wish to build another factory, I must now press `b` and `3` again!

I think that if I switch modes, the secondary-modifier should carry over, such that pressing `u` after `b-3` results in mode `u-3`

**Comment by JCharante** [comment]
The deed has been done, but I need to write down a reminder that this feature **will** return as a client side option
