### ISSUE TITLE
Spelling mistake when you first start playing.

### ISSUE THREAD

**Issue by wilSecord** [baxter-oop/AndOre#164]
Says ANEW instead of A NEW. Simple but makes it look more professional.

**Comment by Julian-B** [comment]
In fact, as sentence *or* phrase "Start a new" is grammatically incorrect, since it lacks a subject.

However, the word [anew](http://www.dictionary.com/browse/anew), while still making this sentence incomplete, is a widly used phrase and perfectly accpetable in this situation.

**Comment by JCharante** [comment]
@wilSecord pwned
