### ISSUE TITLE
Corps not working

### ISSUE THREAD

**Issue by HarrisonCyr** [baxter-oop/AndOre#220]
During the play test this morning no one could join a corp, We went up to each other, hit I and sent an invite to each other and it did nothing. We could still Ally people,

**Comment by JCharante** [comment]
Interesting, that same day I got 4 others into my corp.

**Comment by JCharante** [comment]
Since the code for corps has been rewritten since the issue was created, I'll close this issue. If you observe this again, please reopen this issue with some more details.
