### ISSUE TITLE
Portals are non-Functional

### ISSUE THREAD

**Issue by TheCoub** [baxter-oop/AndOre#239]
When approaching a portal to another world, I am unable to use them. I have attempted Movement mode, Use mode, and Loot mode in all 10 number modifiers. This is true for any portal. 

-Ryan Courbron

**Comment by JCharante** [comment]
How were you playing the game? Were you hosting your own servers or were you using the community run one? If the latter, then it could just be that the majority of the nodes crashed and due to that, you couldn't go into them.

**Comment by TheCoub** [comment]
I was on the community run server, iwanttorule.space. I was on there because we need to do QA and playtesting on there,

**Comment by JCharante** [comment]
I see, well the problem is just that the nodes crashed after running into errors with futures returning None in tasks, the portal code itself is fine.
