### ISSUE TITLE
Chat Whitelist includes bad words

### ISSUE THREAD

**Issue by TheCoub** [baxter-oop/AndOre#246]
The whitelist contains some words, including but not limited to Indian, sex, slave, slavery, and violent. But it lacks other words that are cruical such as wait, please, turret, and spike trap. As it stands, the whitelist is nonfunctional. I have yet to look through the newly added words, but it is clear that some need to be removed.

**Comment by TheCoub** [comment]
Example bad words: I enjoy Indian Sex Slavery, Indians have violent sex.

**Comment by JCharante** [comment]
While you raise good points, we use [Smelter](https://github.com/AI-Productions/smelter) for the whitelist. The bad words in the whitelist is not something that would be solved in this repository.
