### ISSUE TITLE
Game not Connecting

### ISSUE THREAD

**Issue by TheCoub** [baxter-oop/AndOre#259]
After logging into And/Ore,  The game repeatedly shows the `Finding Our World...` message and fails to connect to the game. 
Other (possibly) relevant information:
* System: Connecting...
* Red Square then a Green Square
* RTL: -0ms
* 1 Players Online!
* Region Version: ??????
* Sleipnir Version: 5579376

**Comment by JCharante** [comment]
Are you sure you're going to the right [url](http://andore.online) for the game?

**Comment by TheCoub** [comment]
Ah.  I did not know that the URL was changed.  I would appreciate that if there was a large change like that, that you communicate that in the #general Channel of the slack in the future. Just so everyone is aware.

**Comment by JCharante** [comment]
Well the url was updated in the readme file, the url in the home page of the repo, there's been multiple recent commits about changing the domain, along with the task in the kanbanboard.

**Comment by TheCoub** [comment]
I went to the new URL, and the issue persists. All of the information is the same as before.

**Comment by JCharante** [comment]
Are you sure? I seem to be having no problems. Have you flushed your cache?

![](http://i.imgur.com/TrXjhIL.png)

**Comment by TheCoub** [comment]
Still, I would appreciate using a more consistently checked method of communication, namely Slack. Not just for me, but everyone in the design team would need to know as well, and they do not consistently check Github as they do not need to. 

I just cleared my cache, and the issue persists.

**Comment by JCharante** [comment]
Could you go to the console and see which region you're trying to connect to? I just noticed that the purple server was configured incorrectly, which effects wojtek.

**Comment by TheCoub** [comment]
It is Wojtek.

**Comment by TheCoub** [comment]
It is now attempting to access Scipio, but it is still failing.

**Comment by JCharante** [comment]
The problem affecting Wojtek has now been resolved.

**Comment by JCharante** [comment]
Scipio is now working, it was configured incorrectly (off by 1 typo).

**Comment by TheCoub** [comment]
Thank you for your quick resolution of this. Can we close the issue?

**Comment by JCharante** [comment]
and thank you for your cooperation, I noticed I did not have the best tone.

Seeing as I cannot find any other regions I cannot connect to, then sure close this issue.

If the same problem happens in the future, then this issue can be reopened or referenced.
