### ISSUE TITLE
No loss of ore on starvation death

### ISSUE THREAD

**Issue by halstedlarsson** [baxter-oop/AndOre#38]
Player should lose ore on starvation death. Ideally, an ore pile is left where the player died in the amount of the player's carried ore.

**Comment by JCharante** [comment]
In previous versions you lost the ore you had when you died. Something must have messed it up.

**Comment by JCharante** [comment]
Ore pile waiting on #39

**Comment by JCharante** [comment]
Issue indirectly fixed in https://github.com/baxter-oop/AndOre/issues/39
