### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by JCharante** [baxter-oop/AndOre#72]
Hold Down Shift + direction key to move 3 cells at a time at a cost of 5 ore. The cells in the path must all be passable.

**Comment by Julian-B** [comment]
I would suggest the price being Health, not Ore. Y'know, it takes more endurance and strength to run than it takes cash. 

Though maybe you are purchasing supplements...

**Comment by JCharante** [comment]
@Julian-B That's actually a good idea

**Comment by JCharante** [comment]
Stupidly pushed to master; https://github.com/baxter-oop/AndOre/commit/2c7d6809918a6cf3c067883a1abfa60b84f23cdf

Closing issue as it's now resolved.
